blank_issues_enabled: false

issue_templates:
  - name: Bug Report
    description: Report a bug to help improve VRCi.
    template: bugreport.yml
    title: "[BUG] "
    labels: ["bug", "triage"]

  - name: Feature Request
    description: Propose new features or improvements for VRCi.
    template: feature_request.yml
    title: "[FEATURE] "
    labels: ["enhancement", "proposal"]

contact_links:
  - name: Discussions
    url: https://github.com/VRCiOS/VRCi/discussions
    about: Join community discussions about VRCi to share experiences and tips.

