name: Build README PDF

on:
  push:
    branches:
      - main

jobs:
  build-readme-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-lang-korean \
            latexmk

      - name: Create docs directory
        run: mkdir -p docs

      - name: Convert README.md to PDF
        run: |
          pandoc README.md \
            --pdf-engine=lualatex \
            -V documentclass=article \
            -o docs/README.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: README-pdf
          path: docs/README.pdf
